apiVersion: apps/v1
kind: Deployment
metadata:
  name: s4estaj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s4estaj
  template:
    metadata:
      labels:
        app: s4estaj
    spec:
      containers:
      - name: s4estaj
        image: keremyagiz124/s4estaj:latest
        ports:
        - containerPort: 5000
